favicon: /images/icon.png
banner: /images/icon.png

logo:
  expanded: /images/longLogo.jpg
  collapsed: /images/logo64.png
  dark: /images/icon.png

flag: false
  # - name: for creators
  #   default: true
  #   # icon: flag-cn
  #   index: /index.html

  # - name: for developers
  #   index: https://substack.com

  

search: false

userDefinedSearchData:
  custom: false
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(https://www.baidu.com/favicon.ico)
  hotStatus: true
  data:
    - name: 百度
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=

githubCorner: false

expandAll: false
menu:
  - name: Platforms
    icon: far fa-star
    config: platforms

  - name: Sponsors
    icon: far fa-star
    config: sponsors

  - name: AI Art
    icon: fas fa-tools
    submenu:
      - name: AI Drawing
        icon: fas fa-tools
        config: aiDrawing
      - name: 我的博客
        icon: fas fa-blog
        config: myBlog

platforms:
  - name: YouTube
    url: https://youtube.com/
    img: /images/logos/youtube.png
    description: Bigger video share platform.
  - name: Medium
    url: https://medium.com/
    img: /images/logos/medium.png
    description: Writing platform.

sponsors:
  - name: Me
    description: sponsor to get featured

devTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。

aiDrawing:
  - name: Midjounry
    url: https://blog.hclonely.com/
    description: 专业的绘画软件

about:
  url: https://mrrock.medium.com/
  icon: far fa-heart
  name: My Blog


# aboutPage:
#   website:
#     head: 关于本站
#     html: '<blockquote><p>本站是hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>的demo站。</p></blockquote>'
#   webmaster:
#     head: 关于站长
#     name: HCLonely
#     url: https://blog.hclonely.com/
#     img: /images/logos/myblog.png
#     description: 懒人一个
#     html: '<br /><blockquote><p>本站是<a href="https://github.com/HCLonely">HCLonely</a>基于<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>项目做的一款<a href="https://hexo.io/">Hexo</a>主题。</p></blockquote>'

since: 2023

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: Page Views $pv
  uv: Unique Vistors $uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
